version: "3"
services:
#  Create a service named db.
  db:
    restart: always
    image: "postgres"
    container_name: "diplodogdiplom"
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=diplodog
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data3
  project:
#    restart: always
    build: .
#    links:
#      - db
    depends_on:
      - db



