version: "3"
services:
#  Create a service named db.
  db:
    image: "postgres"
    container_name: "diplodogdiplom"
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=diplodog
    ports:
      - "5434:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data3

